# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BowFolios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BowFolios
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
